# Generated by Django 6.0.4 on 2026-04-24 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50)),
                ('name', models.TextField()),
                ('hours', models.CharField(blank=True, max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MatrixResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('hours_max', models.CharField(blank=True, max_length=20)),
                ('hours_min', models.CharField(blank=True, max_length=20)),
                ('trimester', models.CharField(blank=True, max_length=20)),
                ('weekly_hours', models.CharField(blank=True, max_length=20)),
                ('trimester_hours', models.CharField(blank=True, max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tempus.matrixcompetency')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MatrixUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=50, unique=True)),
                ('project_description', models.TextField(blank=True)),
                ('program_code', models.CharField(db_index=True, max_length=50)),
                ('program_name', models.CharField(max_length=255)),
                ('level', models.CharField(blank=True, max_length=50)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('competency_count', models.PositiveIntegerField(default=0)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matrix_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='matrixcompetency',
            name='matrix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='tempus.matrixupload'),
        ),
    ]
