# Generated by Django 4.2.29 on 2026-04-27 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tempus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=80, unique=True)),
                ('document_number', models.CharField(db_index=True, max_length=40, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('sena_email', models.EmailField(blank=True, max_length=255)),
                ('education_level', models.CharField(blank=True, max_length=120)),
                ('undergraduate', models.TextField(blank=True)),
                ('postgraduate', models.TextField(blank=True)),
                ('coordination', models.CharField(blank=True, max_length=180)),
                ('modality', models.CharField(blank=True, max_length=120)),
                ('specialty', models.TextField(blank=True)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('source_row', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name', 'id'],
            },
        ),
    ]
