# Generated by Django 6.0.4 on 2026-05-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempus', '0007_ficha_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='cdf_trimestres',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
