# Generated by Django 6.0.4 on 2026-05-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempus', '0008_alter_ficha_cdf_trimestres'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='schedule_state',
            field=models.JSONField(blank=True, default=list, help_text='Estado del horario de programación (caché)'),
        ),
    ]
